### ISSUE TITLE
How to use @Getter with Parameters

### ISSUE THREAD

**Issue by RehanSaeed** [ktsn/vuex-class#14]
If I have the following getter setup:

```typescript
const getters: GetterTree<IMyState, any> = {
  // academies: (state, getters) => x.academies,
  academy: (s) => ((id: number) => s.items.find((x) => x.id === id)),
};
```

How can I use the `@Getter` decorator in my component to execute my getter based on a vue property:

```typescript
@Component
export default class MyComponent extends Vue {
  @Prop({required: true})
  public id: number;

  @Getter
  public item
}
```

I want to bind the `id` property of my component and use `@Getter` to retrieve one of a collection of items.

**Comment by econic** [comment]
This is the most obvious use case 
`id prop => getter => object from store`
and i can't find a solution for it o0

**Comment by ktsn** [comment]
Just call the getter.

```ts
@Component
export default class MyComponent extends Vue {
  @Prop({required: true})
  public id: number;

  @Getter
  public item: (id: number) => Item

  created() {
    console.log(this.item(this.id))
  }
}
```

**Comment by axe-me** [comment]
@ktsn 
is that possible to do something like:
```typescript
@Getter('getItem', { id: 1 })
public item!: Item
```
the basic idea is mapping the getter to a variable, so in the component , i dont have to call the getter multiple times.

**Comment by cnjack** [comment]
> Just call the getter.
> 
> ```ts
> @Component
> export default class MyComponent extends Vue {
>   @Prop({required: true})
>   public id: number;
> 
>   @Getter
>   public item: (id: number) => Item
> 
>   created() {
>     console.log(this.item(this.id))
>   }
> }
> ```

is not work for me
```
dialog.ts
const getters: GetterTree<DialogState, RootState> = {
    getUser(state: DialogState, id: number): UserInfo {
        for (const userInfo of state.userList) {
            if (userInfo.user_id === id) {
                return userInfo;
            }
        }
        // TODO get  userInfo from remote
        return demoUser;
    },
};
```

```
main.vue
export default class extends Vue {
        @State('dialog')
        private dialogState!: DialogState;

        @Getter('getUser', {namespace: 'dialog'})
        private getUser!: (state:DialogState, id: number) => UserInfo;

        private getUserAvatar(id: number): string {
            return this.getUser(this.dialogState, id).avatar;
        }
    }
```

TypeError: this.getUser is not a function

**Comment by cnjack** [comment]
is done with
```
getUser: (state: DialogState) => (id: number): UserInfo => {
        for (const userInfo of state.userList) {
            if (userInfo.user_id === id) {
                return userInfo;
            }
        }
        return demoUser;
    },
```

**Comment by SaschaAusUlm** [comment]
I cannot make that work.

In my appliance store:

`  getApplianceState(state: ApplianceStoreState, virtualFridgeId: string): string {
   ....
}`

In my HomeStore:

`export const applianceStoreAccess = namespace('applianceStore');`

In my class:

`import { applianceStoreAccess } from '@/views/HomeStore';
...
  @applianceStoreAccess.Getter getApplianceState: (virtualFridgeId: string) => string;

  public getApplianceStateFromStore(): string {
      if (this.tmpApplianceInfo) {
          let virtualFridgeId: string = this.tmpApplianceInfo.virtualFridgeId;
          return this.getApplianceState(virtualFridgeId);
       }
`

leads to:

[Vue warn]: Error in render: "TypeError: this.getApplianceState is not a function"

What am I doing wrong?

**Comment by Essk** [comment]
> [Vue warn]: Error in render: "TypeError: this.getApplianceState is not a function"
> What am I doing wrong?

I didn't understand this right away either so clarifying for anyone else struggling.

For this use case, the getter function needs to return _another_ function that takes the id as a param. This is what @cnjack demonstrates. Written longhand their solution would look something like this: 

```
getUser: function(state: DialogState) {
    return function( id: number): UserInfo {
      //do lookup stuff and return result
   }
}
```

Hopefully that clears it up a bit :)

**Comment by SaschaAusUlm** [comment]
Thanks, that indeed cleared it up.

Sascha

**Comment by JonUK** [comment]
I hit this issue and found the syntax quite tricky to get right when using the `@Getter` decorator. Below worked for me ("Dispatch" is the type of item in the store that the getter returns):

**Store**
```javascript
export const getters: GetterTree<RecentDispatchesState, RootState> = {
  getDispatchById: (theState: RecentDispatchesState) => (id: string): Dispatch | null => {
    const dispatch = theState.dispatches.find(item => item.id === id);
    return dispatch || null;
  }
};
```

**Component**
```javascript
@Getter('getDispatchById', { namespace: 'recentDispatches' })
getDispatchById!: (id: string) => Dispatch;
```

More information
https://keepinguptodate.com/pages/2019/09/vuex-getter-parameter-typescript/

**Comment by sidyes** [comment]
I still got one question regarding parameterized Getters.
At the moment I have a parametrized getter like this:
```
....
@Getter("getItemByUser", { namespace: "items" })
  getItemByUser!: (user: User) => Item;

public item: Item;

public created(): void {
 this.item = this.getItemByUser(this.user);
}
...
```

The problem now is that the item property does not get updated when something in the state (which is used by the getItemByUser getter) changes.
So it just gets called once and that's it. How can I somehow "subscribe" to this?
A [property-style access getter](https://vuex.vuejs.org/guide/getters.html#property-style-access) automatically updates it value when something changes.

Can you help me out there?
