### ISSUE TITLE
There are multiple modules with names that only differ in casing.

### ISSUE THREAD

**Issue by cyocun** [ktsn/vuex-class#15]
hi.
Thank you for providing a very useful helper
The following warning will be issued when using these.

I can ignore it, but since I want to erase it, can I have an idea?

```
export default class MyPost extends BasePage {
    @State theState: number // <- I get a warning when either one comes in.
    @Mutation theMutation: Function // <- I get a warning when either one comes in.
...
}
```

Warning content is here
```
client? cb1f: 147 ./node_modules/Vuex/dist/vuex.esm.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case - semantic.
```

The environment is
- typescript 2.6.2
- webpack 3

Sorry for the poor English!

**Comment by ktsn** [comment]
This is not reated with vuex-class nor vuex. This warning looks came from webpack.
And it's because you are likely writing `import Vuex from 'Vuex'` instead of `import Vuex from 'vuex'`. Please try using lower case for module names.
