### ISSUE TITLE
Errors after updating to TypeScript 2.7.1

### ISSUE THREAD

**Issue by tbsvttr** [ktsn/vuex-class#17]
Every usage of vuex-class causes the error `Property 'xxx' has no initializer and is not definitely assigned in the constructor.` after updating TypeScript from 2.6.2 to 2.7.1.

**Comment by ktsn** [comment]
Please read TypeScript 2.7 features. You need `definite assignment assertions` since decorated properties does not have initializers.
https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#stricter-class-property-checks

**Comment by tbsvttr** [comment]
Thanks @ktsn! While I could fix this issue new ones arrived in combination with an already known bug in vue-test-utils. https://github.com/vuejs/vue-test-utils/issues/73
