### ISSUE TITLE
Infer the property name in namespaces too

### ISSUE THREAD

**Issue by Samitier** [ktsn/vuex-class#27]
Hello,

Right now, thanks to #1, we can use the decorator without parameters:

```ts
  @State foo
  @Getter bar
  @Action baz
```

But when using modules and namespaces, the decorator parameter is still mandatory:

```ts
const someModule = namespace('path/to/module')

[...]

@someModule.State('foo') foo
```

Would it be possible to infer the property name in namespaces too to make the code more consistent?

Thanks!

**Comment by ktsn** [comment]
Well, you already can omit property name on namespaced helpers. https://github.com/ktsn/vuex-class/blob/master/test/bindings.ts#L81

**Comment by Samitier** [comment]
Oh sure, my bad! 

Thank you @ktsn !
