### ISSUE TITLE
Add the ability to specify a subfield

### ISSUE THREAD

**Issue by yarkovaleksei** [ktsn/vuex-class#28]
I want to use this syntax:

`@State('foo.nested.bar') bar`

Now for these purposes I have to specify the function from which I return the field I need.

`@State(state => state.foo.nested.bar) bar`

**Comment by ktsn** [comment]
I'm not willing to add such feature because:

1. It's impossible to type check.
2. It would provide poor error message if there is typo on property name.
3. Vuex does not support that.
