### ISSUE TITLE
Dynamic namespace

### ISSUE THREAD

**Issue by andredewaard** [ktsn/vuex-class#32]
Is there a way to set the namespace dynamically? 

For example if i have a component that can gets his data from 2 different modules in the store and i send that namespace by prop.

This is not working obviously.
```
@Component
export default class Navigation extends Vue {

  @Prop() private namespace!: string;
  @Getter('documents', { namespace: this.namespace }) private documents!: boolean;
}
```

This works
```
@Component
export default class Navigation extends Vue {

  @Prop() private namespace!: string;

  private get documents(): any {
    return store.getters[`${this.namespace}/documents`];
  }
}
```

**Comment by hkan** [comment]
I think it's technically impossible. Because in current implementation for decorators, you do not have access to the instance. I'm not fully sure though.

**Comment by ktsn** [comment]
It's impossible and I'm not sure the advantage to do that in vuex-class as it would not infer the `this` type.
