### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature. Type 'void' has no compatible call signatures.

### ISSUE THREAD

**Issue by builder7777** [ktsn/vuex-class#33]
I am getting an error when trying to call an action from store:

```TypeScript
import { Component, Vue, Watch } from 'vue-property-decorator';
import { Action } from 'vuex-class';

@Component
export default class extends Vue {
  @Action('itemsFetch', { namespace: 'MainMenu' }) private getMenuItems!: void;

  private mounted() {
    this.getMenuItems();
  }
}
```

The compiler is complaining about `this.getMenuItems()` method call:

`Cannot invoke an expression whose type lacks a call signature. Type 'void' has no compatible call signatures.`

The MainMenu.ts has the following action signature:
```TypeScript
const actions: ActionTree<MenuState, RootState> = {
   // ... other actions ...
    itemsFetch({ commit }): void {
        // ... get some test items ...
        commit('itemsUpdate', items);
    },
};
```
I also tried using   `@menuModule.Action private itemsFetch!: void;` instead of specifying namespace in the decorator - same result.

Am I not using this right or something else is going on?

**Comment by ktsn** [comment]
Because you declare `getMenuItems` as `void` type. Please annotate actual function type.

```ts
@Action(...) private getMenuItems!: () => void
```

**Comment by Uriziel01** [comment]
@ktsn Sorry for digging up old topic, how to use action that take a payload?

I'm gettting `Expected 0 arguments, but got 1.` ERROR when declaring it just like that:
```ts
@Action private loginUser!: () => void

private authenticate (): void {
  this.loginUser({email:this.email, password: this.password});
}
```

**Comment by tehbilly** [comment]
I believe you'd change it to:

```typescript
@Action private loginUser!: (args: any) => void;
```
