### ISSUE TITLE
The computed property ... is already defined in data

### ISSUE THREAD

**Issue by yooouuri** [ktsn/vuex-class#34]
> [Vue warn]: The computed property "currentUser" is already defined in data.

Inside my component I have

```
import { Getter } from 'vuex-class';

....

@Getter('currentUser') private currentUser = '';
```

User module:

```
const getters: GetterTree<UserState, {}> = {
  currentUser: (state: UserState): string => {
    return state.user;
  },
};

....

export const user: Module<UserState, {}> = {
  namespaced: false,
  state: initialState,
  getters,
  actions,
  mutations,
};
```

![image](https://user-images.githubusercontent.com/12934957/47987947-25214180-e0e1-11e8-8141-d2b08f805e8e.png)

Calling an action does work!

What am I doing wrong?

**Comment by ktsn** [comment]
You shouldn't initialize the property since it will be created as computed property.
