### ISSUE TITLE
Question about Syntax (TS)

### ISSUE THREAD

**Issue by csigmanek** [ktsn/vuex-class#37]
Hi there,
i tryed using your library with one of these lines:

```
@Getter activeQuiz;
@Getter('activeQuiz') activeQuiz;
```
but i get prompted that

Member 'activeQuiz' implicitly has an 'any' type.
[tslint] The class property 'activeQuiz' must be marked either 'private', 'public', or 'protected' (member-access) [member-access]

Do you have any idea how to write that properly? Thanks in advance.
A common computed is written like this:
`private get currentScore(): string {return ''}` if that helps (using vue-property decorator).

**Comment by ktsn** [comment]
As error message said, you need to annotate your property by type and accessor (either public, private or protected).

**Comment by csigmanek** [comment]
Well I do know that the message says that. But i have no idea how to do that. That's why I was hoping for a small example.
