### ISSUE TITLE
How can I map module states ?

### ISSUE THREAD

**Issue by Allenice** [ktsn/vuex-class#4]
@State('s') is map the root state, but how can I map a state from modules?
I can use @State(function (state) { return state.ma.s }) map the module **ma** state **s**, but I think
It can use an easy way to meet it. For example: @State('ma.s'), ma is a module name

**Comment by hworld** [comment]
Just ran into this as well. A way to split on periods to go deeper into the chain would be great!

**Comment by jackple** [comment]
@Allenice  
How do you solve it now?

**Comment by jackple** [comment]
I use it this way now:
```
const _namespace = 'home',
  HomeState = namespace(_namespace, State),
  HomeGetter = namespace(_namespace, Getter),
  HomeMutation = namespace(_namespace, Mutation),
  HomeAction = namespace(_namespace, Action)
```
I think there is a better way!
