### ISSUE TITLE
Helper file

### ISSUE THREAD

**Issue by mailok** [ktsn/vuex-class#42]
Why can not I use the decorators in a file that is not a component?
I write that in my helper.ts
```
@Getter(GetterType.ERROR) getterError;
```
but show me error.
i what export getterError
![captura](https://user-images.githubusercontent.com/3769277/50301555-a9434480-0455-11e9-8c0a-2166c53e79cd.PNG)

**Comment by ktsn** [comment]
Decorator cannot be used by such usage. You need to use it with class declaration, method, accessor or property. 
https://www.typescriptlang.org/docs/handbook/decorators.html
