### ISSUE TITLE
How create Helpers file

### ISSUE THREAD

**Issue by mailok** [ktsn/vuex-class#44]
I want to separate all the logic from my state of the components in a file, and then use that file in multiple components, I create a file called helper.ts, 
but I do not know how to make it work for me, I did a class:
``` 
import { ActionType, GetterType } from './types';
import { Action, Getter } from 'vuex-class';
import { Vue } from 'vue-property-decorator';

class Helpers extends Vue {
    @Getter(GetterType.IS_USER_LOGGED) isUserLogged: () => boolean;
    @Action(ActionType.LOGIN) login: (credentials: any) => void;
}

export default new Helpers();
```
But this does not work on the components, could someone help me?

**Comment by ktsn** [comment]
1. You always need `@Component` decorator when using vuex-class decorators.
2. You cannot use it from independent instance which is not mounted as descendant of the root instance because the store instance is not injected in that case.

You may want to inherit such helper logic to some component.

```ts
@Component
class Helpers extends Vue {
    @Getter(GetterType.IS_USER_LOGGED) isUserLogged: boolean;
    @Action(ActionType.LOGIN) login: (credentials: any) => void;
}

@Component
class SomeComponent extends Helpers {
  created() {
    console.log(this.isUserLogged)
  }
}
```
