### ISSUE TITLE
Status of typed store?

### ISSUE THREAD

**Issue by hworld** [ktsn/vuex-class#5]
Just curious what the status of the typed-store branch is. It'd be really really great to have typescript warn when I'm using the wrong key when committing and dispatching and what not. I'm thinking that the typed-store branch provides this?

**Comment by ktsn** [comment]
It's just experimental code and won't be released because I realized it actually isn't scope of this library and it's less practical for almost users. But maybe I would separate it as other library.

**Comment by hworld** [comment]
ah, okay, thanks for the info
