### ISSUE TITLE
typescript cannot infer type

### ISSUE THREAD

**Issue by 0x8f701** [ktsn/vuex-class#51]
## Questions

Typescript cannot infer correctly the type, am I wrong somewhere?

![Screenshot from 2019-03-30 13-00-47](https://user-images.githubusercontent.com/33961674/55276081-5e0bbe00-52ef-11e9-8e43-06d9c1846bc5.png)

**Comment by austindebruyn** [comment]
This fixed it for me: https://github.com/ktsn/vuex-class/issues/33#issuecomment-433074018

Try `@AclModule.Mutation(UPDATE_ACL_FILTER) updateAclFilter!: () => void;`

**Comment by 0x8f701** [comment]
@austindebruyn  Thanks! It works like a charm!

**Comment by kamok** [comment]
Why can't we use TypeScript implicit typing? We have access to the Actions and its typing. Is there a way to make it work?

**Comment by StummeJ** [comment]
Because of decorators not being able to set the type of what it's decorating.... Composition API gives you the ability to infer types.
