### ISSUE TITLE
Add mapping function as the second param for Getter

### ISSUE THREAD

**Issue by maksnester** [ktsn/vuex-class#53]
Would be nice to have additional mapping function as we have already for State. To be able to do something like that:

```ts
@Getter('some', (val) => val.map(item => item.id)) someIds
```

**Comment by mduqueoviedo** [comment]
Isn't [this](https://github.com/ktsn/vuex-class/issues/14#issuecomment-341632858) enough?

**Comment by maksnester** [comment]
@mduqueoviedo I don't remember what problem I tried to solve, but solution from your link looks good to me. 

In case when custom function is needed - `@State` accepts mapping fn. Getter is possible to just call, no point to change getter with mapping function I think.
